name: pablosaraiva
version: 0.0.1
description: pablosaraiva.com
environment:
  sdk: 1.8.5
dependencies:
  browser: 0.10.0+2
  polymer: 0.15.5+3
transformers:
- polymer:
    entry_points: web/index.html
    lint: false   