name: pablosaraiva
version: 0.0.1
description: pablosaraiva.com
environment:
  sdk: 1.9.1
dependencies:
  browser: '>=0.10.0 <0.11.0'
  polymer: '>=0.15.5 <0.16.0' 
transformers:
- polymer:
    entry_points: web/index.html
    lint: false   