name: pablosaraiva
version: 0.0.1
description: pablosaraiva.com
environment:
  sdk: 1.10.0
dependencies:
  browser: ">=0.10.0 <0.11.0"
  polymer: ">=0.16.1 <0.17.0"
  core_elements: ">=0.7.1 <0.8.0"
  markdown: ">=0.7.1+2 <0.8.0"
  route_hierarchical: ">=0.6.1 <0.7.0"
transformers:
- polymer:
    entry_points: web/index.html
    lint: false
